--ATIVIDADE 11
-- QUANTOS PRODUTOS TEMOS CADASTRADO NO SISTEMA QUE CUSTAM MAIS QUE 1500 REAIS?

SELECT count(*)
FROM Production.Product
WHERE listPrice > 1500;
--(39) produtos

--ou
SELECT count(listprice)
FROM Production.Product
WHERE listPrice > 1500;

-- ATIVIDADE 12
-- QUANTAS PESSOA TEMOS COM O SOBRENOME QUE INICIA COM A LETRA P?

SELECT COUNT(LastName)
FROM Person.Person
WHERE LastName LIKE 'P%';
--(1187) sobrenomes

--ATIVIDADE 13
-- EM QUANTAS CIDADE ÚNICAS ENTÃO CADASTRADOS NOSSOS CLIENTES?

SELECT count(DISTINCT city)
FROM Person.Address;
--(575) cidades

--ATIVIDADE 14
-- QUAIS São ESSAS CIDADES?
SELECT DISTINCT city
FROM Person.Address;

--ATIVIDADE 15
--QUANTOS PRODUTOS VERMELHOS TEM PREÇOES ENTRE 500 Á 1000 REAIS?
SELECT COUNT(*)
FROM Production.Product
WHERE color in ('red') AND ListPrice BETWEEN 500 AND 100;
--(0) PRODUTOS

--ATIVIDADE 16
--QUANTOS PRODUTOS CADASTRADOS TEM A PALAVRA ROAD NO NOME DELES?
SELECT COUNT(*)
FROM Production.Product
WHERE NAME LIKE '%ROAD%';
--(103) PRODUTOS





