-- CHAVE PRIMÁRIA É UMA COLUNA OU GRUPO DE COLUNAS, USADA PARA IDENTIFICAR
-- UNICAMENTE UMA LINHA EM UMA TABELA
-- VOCE CONSEGUE CRIAR ESSAS CHAVES PRIMÁRIAS ATRAVÉS DE RESTRIÇOES(CONSTRAINTS)
-- QUE SÁO REGRAS QUE VOCE DEFINE QUANDO ESTÁ CRIANDO UMA COLUNA
-- QUANDO VOCE FAZ ISSO VOCE ESTA CRIANDO UM INDICE UNICO PARA AQUELA COLUNA OU
-- GRUPO DE COLUNAS

CREATE TABLE nome_Tabela (
    nome_Coluna tipoDeDados PRIMARY KEY
    nome_Coluna tipoDeDados ...
)

-- CAMPO QUE NUNCA VAI SER REPETIDO

-- CHAVE ESTRANGEIRA É UMA COLUNA OU GRUPO DE COLUNAS EM UMA TABELA QUE IDENTIFICA
-- UNICAMENTE UMA LINHA EM OUTRA TABELA
-- OU SEJA, UMA CHAVE ESTRANGEIRA É DEFINIDA EM UMA TABELA ONDE ELA É APENAS
-- UMA REFERENCIA E NAO CONTEM TODOS OS DADOS ALI
-- ENTAO UMA CHAVE ESTRANGEIRA É SIMPLESMENTE UMA COLUNA OU GRUPO DE COLUNAS QUE É
-- UMA CHAVE PRIMARIA EM OUTRA TABELA

-- UMA TABELA QUE CONTEM  A CHAVE ESTRANGEIRA É CHAMADA DE TABELA REFERENCIADORA  OU TABELA FILHO. E A TABELA NA QUAL A CHAVE
-- ESTRANGEIRA É REFERENCIADA É CHAMADA DE TABELA REFERENCIADA OU TABELA PAI
-- UMA TABELA PODE TER MAIS DE UMA CHAVE ESTRANGEIRA DEPENDENDO DO SEU RELACIONAMENTO
-- COM AS OUTRAS TABELAS.


-- REGRAS:

-- NO SQL SERVER VOCE DEFINE UMA CHAVE ESTRANGEIRA ATRAVEZ DE UM "FOREIGN KEY CONSTRAINT" OU
-- RESTRIÇAO DE CHAVE ESTRANGEIRA
-- UMA RESTRIÇAO DE CHAVE ESTRANGEIRA INDICA QUE OS VALORES EM UMA COLUNA OU GRUPO DE COLUNAS NA TABELA FILHO CORRESPONDEM AOS VALORES NA TABELA PAI
-- NOS PODEMOS ENTENDER QUE UMA CHAVE ESTRANGEIRA MANTEM A "INTEGRIDADE REFERENCIAL"