-- CHECK CONSTRAINT CRIA RESTRIÇOES DE VALORES QUE PODEM SER INSERIDOS EM UMA COLUNA DE UMA TABELA 
-- EM BANCO DE DADOS QUANDO VOCE ESTA CRIANDO UMA NOVA TABELA

CREATE TABLE CarteiraMotorista (
    Id INT NOT NULL,
    Nome VARCHAR(225) NOT NULL,
    Idade INT CHECK (Idade >= 18)
);

-- SE VOCE TENTAR CRIAR UMA LINHA DE COLUNA COM A IDADE MENOR QUE 18, DA ERRO