-- COUNT da o número de linhas(PRODUTOS) que bate com a condição que foi definida

SELECT COUNT(*)
FROM tabela

-- Caso quiser saber o número de linhas de algo específico é só colocar dentro do parenteses
SELECT COUNT(coluna1)
FROM tabela

--Caso quiser contar o número de linhas mas sem incluir algo duplicado, use DISTINCT
SELECT COUNT(DISTINCT coluna2)
FROM tabela

-- EXEMPLO DE COMO USAR COUNT, AQUI ELE VAI DIZER A QUANTIDADE DE LINHAS QUE FORAM USADA NA TABELA PERSON.PERSON
SELECT COUNT(*)
FROM Person.Person;

--AQUI AGORA É SO PRA SABER A CONTAGEM DE LINHAS DA COLUNA TITLE DA TABELA PERSON.PERSON
SELECT COUNT(Title)
FROM Person.Person;

-- QUANTIDADE DE TITULOS SEM NADA DUPLICADO
SELECT COUNT(DISTINCT Title)
FROM Person.Person;


--ATIVIDADE 6
-- QUANTOS PRODUTOS TEMOS CADASTRADO EM NOSSA TABELA DE PRODUTOS

--RESPOSTA:
SELECT COUNT(*)
FROM Production.Product
--(504) PRODUTOS

--ATIVIDAE 7
-- QUANTOS TAMANHOS DE PRODUTOS TEMOS CADASTRADO
SELECT COUNT(Size)
FROM Production.Product
--(211) TAMANHOS

--ATIVIDADE 8
--QUANTOS TAMANHOS DE PRODUTOS TEMOS CADASTRADO SEM NADA DUPLICADO
SELECT COUNT(DISTINCT Size)
FROM Production.Product
--(18) TAMANHOS

