-- CRIAR TABELA DO ZERO

-- SEGUINDO A SEGUINTE SINTAXE:

CREATE TABLE nome_Tabela (
    coluna1 tipo restricaoDaColuna,
    coluna2 tipo restricaoDaColuna,
    coluna3 tipo restricaoDaColuna,
    ...
);


-- PRINCIPAIS RESTRIÇOES

-- NOT NULL - NAO PERMITE NULOS, SEMPRE TEM QUE TER VALOR DENTRO DA COLUNA
-- UNIQUE - FORÇA QUE TODOS OS VALORES EM UMA COLUNA SEJAM DIFERENTES
-- PRIMARY KEY - UMA JUNÇAO DE NOT NULL E UNIQUE, POR EXEMPLO OS ID
-- FOREIGN KEY - IDENTIFICA unicamente UMA LINHA EM OUTRA TABELA
-- CHECK - FORÇA UMA CONDICAO ESPECIFICA EM UMA COLUNA
-- DEFAULT - FORÇA UM VALOR PADRAO QUANDO NENHUM VALOR É PASSADO




-- PROJETO YOUTUBE LITE

CREATE TABLE Canal (
    CanalID int PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    ContagemInscritos INT DEFAULT 0,
    DataCriacao DATETIME NOT NULL
);

CREATE TABLE  Video(
    VideoID INT PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    Visualizacoes INT DEFAULT 0,
    Likes INT DEFAULT 0,
    Dislikes INT DEFAULT 0,
    Duracao INT NOT NULL,
    CanalId INT FOREIGN KEY REFERENCES Canal(CanalId)
);