-- DELETE VAI APAGAR TUDO, ENTAO É RECOMENDADO USAR ELE COMO WHERE CONDICAO

DELETE FROM nomeTabela
WHERE condicao


-- QUERO APAGAR UMA LINHA SÓ QUE ESTA ESCRITO Nome

DELETE FROM Aula 
WHERE Nome = 'Nome'

-- SE VOCE TIRAR O WHERE, ELE APAGA TUDO

