-- DROP TABLE EXCLUI UMA TABELA DE BANCO DE DADOS

DROP TABLE nomeTabela

 -- AGORA SE VOCE QUISER APAGAR APENAS O CONTEUDO DA TABELA SEM SER A TABELA TODA USE TRUNCATE

 TRUNCATE nomeTabela

 