--GROUP BY DIVIDE O RESULTADO DA SUA PESQUISA EM GRUPOS

-- PARA CADA GRUPO VOCE PODE APLICAR UMA FUNÇAO DE AGREGAÇAO, POR EXEMPLO:
-- CALCULAR A SOMA DE ITENS.
-- CONTAR O NÚMERO DE ITENS NAQUELE GRUPO.

SELECT coluna1, funcaoAgregaçao(coluna2)
FROM nomeTabela
GROUP BY coluna1;


--Nesse exemplo primeiro eu somei todos os UnitPrice e agrupei com SpecialOfferID e depois os mostrei separado.

SELECT *
FROM Sales.SalesOrderDetail;

SELECT SpecialOfferID, SUM (UnitPrice) AS "SOMA"
FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID;

SELECT SpecialOfferID, UnitPrice
FROM Sales.SalesOrderDetail
WHERE SpecialOfferID = 9;

-- QUANTOS DE CADA PRODUTO FOI VENDIDO ATÉ HOJE?
SELECT ProductID, COUNT(ProductID) AS "CONTAGEM"
FROM Sales.SalesOrderDetail
GROUP BY ProductID;

-- QUANTOS NOMES DE CADA NOME TEM CADASTRADO NO BANCO DE DADOS
SELECT FirstName, COUNT(FirstName)
FROM Person.Person
GROUP BY FirstName;

-- NA TABELA PRODUCTION.PRODUCT QUERO SABER A MÉDIA DE PREÇOS PARA OS PRODUTOS QUE SaO PRATAS
SELECT color, AVG (ListPrice) "Preço"
FROM Production.Product
WHERE color = 'silver'
GROUP BY color;

--ATIVIDADE 17 
--QUANTAS PESSOAS TEM O MESMO MIDDLENAME AGRUPADAS NO MIDDLE NAME
SELECT MiddleName, COUNT(MiddleName)
FROM Person.Person
GROUP BY MiddleName;

--ATIVIDADE 18
-- EU PRECISO SABER EM MÉDIA QUANTOS PRODUTOS SAO VENDIDOS NA LOJA
SELECT ProductId, AVG(OrderQty) "Média"
FROM Sales.SalesOrderDetail
GROUP BY ProductId;

--ATIVIDADE 19
-- QUAIS FORAM OS PRODUTOS AS 10 VENDAS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA
-- POR PRODUTO DO MAIOR VALOR PARA O MENOR
SELECT TOP 10 ProductID, SUM(LineTotal)
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LineTotal) desc;


--ATIVIDADE 20
-- QUANTOS, QUAIS E A MÉDIA DE PRODUTOS TEM CADASTRADOS NA WORKORDER (ORDEM DE SERVIÇO),
-- AGRUPADOS POR PRODUCTID
SELECT ProductId, COUNT(ProductID) "Contagem",
AVG (OrderQty) "Média"
FROM Production.WorkOrder
GROUP BY ProductId;