--IN É USADO JUNTAMENTE COM WHERE, PARA VERIFICAR SE UM DADO CORRESPONDE A LISTA DE VALOR;

--valor In(valor1, valor2) 
-- ex de cor: 
 color IN('BLUE', 'RED')
--ASSIM ESPECIFIQUEI QUAIS CORES EU QUERO, ENTÃO ELE VAI PROCURAR NO BANCO DE DADOS OS DADOS QUE CORRESPONDEM PELO MENOS UM DOS VALORES


-- QUERO SABER O NÚMERO DO ID DOS FUNCIONÁRIO 7, 2 E 13
SELECT *
FROM Person.Person
WHERE BusinessEntityID IN ('7', '2', '13' );

-- SE FOSSE SEM O IN SERIA:
SELECT *
FROM Person.Person
WHERE BusinessEntityID = 7
OR BusinessEntityID = 2
OR BusinessEntityID = 13;


-- SE USAR O NOTE ELE FAZ O OPOSTO
SELECT *
FROM Person.Person
WHERE BusinessEntityID NOT IN ('7', '2', '13' );





