-- INSERT INTO PODE SER USADO QUANDO VOCE JA TEM UMA TABELA E QUER INSERIR DADOS NELA
-- OU QUANDO VOCE QUER CRIAR UMA TABELA USANDO INSERT INTO

INSERT INTO nomeTabela(coluna1, coluna2,...)
VALUE(valor1, valor2)

-- CASO QUISER INSERIR VARIAS LINHA AO MESMO TEMPO:

INSET INTO nomeTabela(coluna1, coluna2,...)
VALUES(valor1, valor2)
VALUES(valor1, valor2)
VALUES(valor1, valor2)
VALUES(valor1, valor2)

-- CASO QUISER INSERIR INFORMAÇOES DE UMA OUTRA TABELA EM UMA TABELA EXISTENTE

INSERT INTO TabelaA (coluna1)
SELECT coluna2
FROM TabelaB 


-- CRIEI UMA TABELA AULA E INSERI NOME E ID

CREATE TABLE Aula (
    id INT PRIMARY KEY,
    Nome VARCHAR(200)
)

SELECT *
FROM Aula;

INSERT INTO Aula (id, Nome)
VALUES(1, 'Aula 1')

-- AGORA QUERO INSERIR VARIAS INFORMAÇOES AO MESMO TEMPO

INSERT INTO Aula (id, Nome)
VALUES
(2, 'Aula 2'),
(3, 'Aula 3'),
(4, 'Aula 4');

-- SE VOCE QUER INSERIR DADOS DE OUTRA TABELA EM UMA EXISTENTE DE UMA FORMA RAPIDA:
-- NESSE CASO CRIEI UMA TABELA CHAMADA TABELA NOVA E INSERIR OS DADOS DA TABELA AULA

SELECT * INTO TabelaNova FROM Aula;

SELECT *
FROM TABELANOVA;





