-- LEFT OUTER JOIN ou LETF JOIN  RETORNA TODOS DA TABELA A (POR EXEMPLO) E RETORNA DA TABELA B SOMENTE OS IGUAIS
-- A TABELA A, OS DIFERENTES DA TABELA B, ELE COMPLETA COM NULL

SELECT *
FROM TabelaA
LEFT OUTER JOIN TabelaB.nome ON TabelaA.nome = TabelaB.nome



-- QUERO SABER QUAIS PESSOAS TEM UM CARTAO DE CREDITO REGISTRADO
SELECT *
FROM Person.Person AS PP
INNER JOIN Sales.PersonCreditCard PC ON PP.BussinessEntityID = PC.BussinessEntityID
-- INNER JOIN TEVE 19118 NÚMEROS DE RESULTADOS

SELECT *
FROM Person.Person AS PP
LEFT JOIN Sales.PersonCreditCard PC ON PP.BussinessEntityID = PC.BussinessEntityID
-- LEFT JOIN TEVE 19972 NÚMEROS DE RESULTADOS
-- LEFT TROUXE ATÉ OS DADOS QUE NAO ESTAVAM PREENCHIDOS (NULL), ELE FAZ ISSO PRIMEIRO E DEPOIS TRAZ O QUE TEM CARTAO DE CREDITO
-- FAZENDO 19118 MENOS 19972 DA 854, 854 SAO AS PESSOAS QUE NAO TEM CARTAO DE CREDITO REGISTRADO
SELECT 19972 - 19118
-- ENTAO LEFT TROUXE BEM MAIS INFORMAÇOES


-- AGORA OS QUE NAO TEM CARTAO DE CREDITO (NULL)
SELECT *
FROM Person.Person AS PP
INNER JOIN Sales.PersonCreditCard PC ON PP.BussinessEntityID = PC.BussinessEntityID
WHERE PC.BussinessEntityID IS NULL