-- NOT NULL CONSTRAINT SAO RESTRIÇOES QUE FORÇAM COM QUE NAO SEJA POSSIVEL INSERIR DADOS EM 
-- UMA TABELA SEM PREENCHER A COLUNA MARCADA COM NOT NULL 

CREATE TABLE CarteiraMotorista (
    Id INT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Idade INT CHECK(Idade >= 18) 
);

-- NOME, E ID POR EXEMPLO É OBRIGATORIO QUE SEJA PREENCHIDO, POR ISSO O NOT NULL.
-- SE VOCE TENTAR INSERIR OS VALORES E ESQUECER SE INSERIR O NOME POR EXEMPLO QUE POSSUI NOT NULL, ELE DA ERRO


