-- FUNCOES MATEMATICAS

--SE VOCE QUER SOMAR DIFERENTES COLUNAS USE +
SELECT UnitPrice + LineTotal
FROM Sales.SalesOrderDetail;

--SE VOCE QUER SUBTRAIR DIFERENTES COLUNAS USE -
SELECT UnitPrice - LineTotal
FROM Sales.SalesOrderDetail;

--SE VOCE QUER MULTIPLICAR DIFERENTES COLUNAS USE*
SELECT UnitPrice * LineTotal
FROM Sales.SalesOrderDetail;

--SE VOCE QUER DIVIDIR DIFERENTES COLUNAS USE /
SELECT UnitPrice / LineTotal
FROM Sales.SalesOrderDetail;

--SE VOCE QUER SABER A MÉDIA USE AVG
SELECT AVG(UnitPrice)
FROM Sales.SalesOrderDetail;

--SE VOCE QUER SOMAR UMA COLUNA USE SUM
SELECT SUM(UnitPrice)
FROM Sales.SalesOrderDetail;

--SE VOCE QUER VALOR MÍNIMO DE UMA COLUNA USE MIN
SELECT MIN(UnitPrice)
FROM Sales.SalesOrderDetail;

--SE VOCE QUER VALOR MÁXIMO DE  UMA COLUNA USE MAX
SELECT MAX(UnitPrice)
FROM Sales.SalesOrderDetail;

--SE VOCE QUER ARREDONDAR UMA COLUNA PARA UM NÚMERO ESPECIFICO USE ROUND
SELECT ROUND(UnitPrice, 2) --USEI DOIS COMO EXEMPLO
FROM Sales.SalesOrderDetail;

--SE VOCE QUER RAIZ QUADRADA DE UMA COLUNA USE SQRT
SELECT SQRT(UnitPrice)
FROM Sales.SalesOrderDetail;

