-- 1. BOLEANOS
-- 2. CARACTERE
-- 3. NÚMEROS
-- 4. TEMPORAIS


-- BOLEANOS
-- INICIALIZADO COMO NULO, PODE RECEBER TANTO 1 OU 0
--BIT

-- CARACTERE
-- TAMANHO FIXO, PERMITE APENAS UMA QUANTIDADE FIXA DE CARACTERE

-- NÚMEROS
-- VALORES EXATOS
-- TINYINT :  VALORES INTEIROS, SEM 1.4, 1,6 ETC.
-- SMALLINT : MESMA COISA MAS COM LIMITE MAIOR QUE TINYINY
-- INT : MESMA COISA POREM LIMITE MAIOR SMALLINY
-- BIGINT - MESMA COISA POREM LIMITE MAIOR QUE INT
-- NUMERIC OU DECIMAL : VALORES EXATOS, POREM TE PERMITE USAR TAMBEM VALORES FRACIONADOR COMO 5,2 6.0 ETC. E ESCALA AJUDA A DECIDIR A QUANTIDADE DE NÚMEROS FRACIONADOS QUE VOCE POR USAR (5,2) 113,22 EX

-- VALORES APROXIMADOS
-- REAL: TEM UMA PRECISAO DE ATÉ 15 DÍGITOS, APOS A VIRGULA
-- FLOAT : MESMA COISA

-- VALORES TEMPORAIS
-- DATE : ARMAZENA DATA NO FORMATO AAAA/MM/DD
-- DATETIME - ARMAZENA DATA E HORA NO FORMATO AAAA/MM/DD:MM:SS
-- DATETIME2 - MESMA COISA POREM ADICIONANDO MILISEGUNDOS 
-- SMALLDATETIME - DATA E HORA POREM LIMITADO
-- TIME - HORAS, MINUTOS, SEGUNDOS, MILISEGUNDOS POREM LIMITADO
-- DATETIMEOOFSET -- DATA E HORA E FUSO HORARIO

