-- UNIQUE PERMITE TER COLUNAS UNICAS, POREM DIFERENTE DE PRIMARY KEY, PODE EXISTIR VÁRIAS COLUNAS COM
-- A RESTRIÇAO UNIQUE

-- ELA AJUDA A NAO TER DADOS REPITIDOS NA TABELA

CREATE TABLE CarteiraMotorista (
    Id INT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Idade INT CHECK(Idade >= 18),
    CodigoCNH INT NOT NULL UNIQUE
);

-- ELA PODE PERMITIR MESMO NOME, MESMA IDADE MAS NAO O MESMO CODIGO DO CNH

-- SE VC TENTAR INSERIR O CODIGO CNH IGUAL, ELE DA ERRO

