-- VIEWS SAO TABELAS CRIADAS PARA CONSULTA ONDE VOCE USA OUTRAS TABELAS COMO BASE PARA CRIAR UMA NOVA TABELA 
-- DE PESQUISA COM APENAS DADOS ESPECIFICOS QUE VOCE PRECISA DE UMA TABELA.

CREATE VIEWS [Pessoas Simplificado] AS 
SELECT FirstName, MiddleName, LastName
FROM Person.Person
WHERE Title = 'Ms.'

-- AGORA SE VOCE PESQUISAR SOBRE ESSA TABELA ELA VAI TRAZER AS INFORMAÇOES QUE VOCE PEDIU

SELECT *
FROM [Pessoas Simplificado]

-- ELE É UTIL QUANDO VOCE QUER VISUALIZAR APENAS ALGUMAS INFORMAÇOES.